import os

os.system('python3 finetune_model.py --model_type biolinkbert --orig_model_name_or_path biolinkbert --model_name_or_path /net/kdinxidk03/opt/NFS/75y/data/qa/output/biolinkbert-squad/ --output_dir /net/kdinxidk03/opt/NFS/75y/data/OTMRC_PAPER/ --output_model_dir /net/kdinxidk03/opt/NFS/75y/data/qa/output/biolinkbert-squad-otquad-fold1-sequential/ --data_dir /net/kdinxidk03/opt/NFS/75y/data/qa/dataset_pos/otquad/ --train_file train_otquad_fold_1.json  --dataset_name otquad_fold1 --do_lower_case --do_train --max_seq_length 384 --doc_stride 128 --per_gpu_train_batch_size 24 --num_train_epochs 3.0 --learning_rate  3e-5 --overwrite_output_dir --overwrite_output_model_dir')

os.system('python3 finetune_model.py --model_type biolinkbert --orig_model_name_or_path biolinkbert --model_name_or_path /net/kdinxidk03/opt/NFS/75y/data/qa/output/biolinkbert-squad/ --output_dir /net/kdinxidk03/opt/NFS/75y/data/OTMRC_PAPER/ --output_model_dir /net/kdinxidk03/opt/NFS/75y/data/qa/output/biolinkbert-squad-otquad-fold2-sequential/ --data_dir /net/kdinxidk03/opt/NFS/75y/data/qa/dataset_pos/otquad/ --train_file train_otquad_fold_2.json  --dataset_name otquad_fold2 --do_lower_case --do_train --max_seq_length 384 --doc_stride 128 --per_gpu_train_batch_size 24 --num_train_epochs 3.0 --learning_rate  3e-5 --overwrite_output_dir --overwrite_output_model_dir')

os.system('python3 finetune_model.py --model_type biolinkbert --orig_model_name_or_path biolinkbert --model_name_or_path /net/kdinxidk03/opt/NFS/75y/data/qa/output/biolinkbert-squad/ --output_dir /net/kdinxidk03/opt/NFS/75y/data/OTMRC_PAPER/ --output_model_dir /net/kdinxidk03/opt/NFS/75y/data/qa/output/biolinkbert-squad-otquad-fold3-sequential/ --data_dir /net/kdinxidk03/opt/NFS/75y/data/qa/dataset_pos/otquad/ --train_file train_otquad_fold_3.json  --dataset_name otquad_fold3 --do_lower_case --do_train --max_seq_length 384 --doc_stride 128 --per_gpu_train_batch_size 24 --num_train_epochs 3.0 --learning_rate  3e-5 --overwrite_output_dir --overwrite_output_model_dir')

os.system('python3 finetune_model.py --model_type biolinkbert --orig_model_name_or_path biolinkbert --model_name_or_path /net/kdinxidk03/opt/NFS/75y/data/qa/output/biolinkbert-squad/ --output_dir /net/kdinxidk03/opt/NFS/75y/data/OTMRC_PAPER/ --output_model_dir /net/kdinxidk03/opt/NFS/75y/data/qa/output/biolinkbert-squad-otquad-fold4-sequential/ --data_dir /net/kdinxidk03/opt/NFS/75y/data/qa/dataset_pos/otquad/ --train_file train_otquad_fold_4.json  --dataset_name otquad_fold4 --do_lower_case --do_train --max_seq_length 384 --doc_stride 128 --per_gpu_train_batch_size 24 --num_train_epochs 3.0 --learning_rate  3e-5 --overwrite_output_dir --overwrite_output_model_dir')

os.system('python3 finetune_model.py --model_type biolinkbert --orig_model_name_or_path biolinkbert --model_name_or_path /net/kdinxidk03/opt/NFS/75y/data/qa/output/biolinkbert-squad/ --output_dir /net/kdinxidk03/opt/NFS/75y/data/OTMRC_PAPER/ --output_model_dir /net/kdinxidk03/opt/NFS/75y/data/qa/output/biolinkbert-squad-otquad-fold5-sequential/ --data_dir /net/kdinxidk03/opt/NFS/75y/data/qa/dataset_pos/otquad/ --train_file train_otquad_fold_5.json  --dataset_name otquad_fold5 --do_lower_case --do_train --max_seq_length 384 --doc_stride 128 --per_gpu_train_batch_size 24 --num_train_epochs 3.0 --learning_rate  3e-5 --overwrite_output_dir --overwrite_output_model_dir')
